export const demoData = [
  {
    id: "r1",
    type: "restaurant",
    name: "Gaetano's Restaurant",
    imgUrl: "https://images.otstatic.com/prod/28761215/3/large.jpg",
    cuisine: "Italian",
    location: "Torrance / Carson",
    rating: 4.8,
    numRatings: 1097,
    priceRange: 2,
    numBookedToday: 23,
    address: "2731 Pacific Coast Highway Torrance, CA 90505",
    phoneNumber: "(310) 326-3354",
    deliveryPartners: ["Postmates", "UberEats"],
  },
  {
    id: "r2",
    type: "restaurant",
    name: "Cavatina at Sunset Marquis",
    imgUrl: "https://images.otstatic.com/prod/25852939/1/large.jpg",
    cuisine: "Californian",
    location: "West Hollywood",
    rating: 4.5,
    numRatings: 703,
    priceRange: 3,
    numBookedToday: 7,
    address: "1200 Alta Loma Road West Hollywood, CA 90069",
    phoneNumber: "(310) 358-3704",
    deliveryPartners: ["UberEats"],
  },
  {
    id: "r3",
    type: "restaurant",
    name: "Faith & Flower",
    imgUrl: "https://images.otstatic.com/prod/25146094/1/large.jpg",
    cuisine: "Californian",
    location: "DTLA",
    rating: 4.6,
    numRatings: 2305,
    priceRange: 2,
    numBookedToday: 12,
    address: "705 W. 9th Street Los Angeles, CA 90015",
    phoneNumber: "(213) 239-0642",
    deliveryPartners: ["Caviar", "Postmates"],
  },
  {
    id: "r4",
    type: "restaurant",
    name: "Angelini Osteria",
    imgUrl: "https://images.otstatic.com/prod1/31033724/3/large.jpg",
    cuisine: "Italian",
    location: "Beverly / Fairfax / La Brea / Third St.",
    rating: 4.8,
    numRatings: 1029,
    priceRange: 3,
    numBookedToday: 15,
    address: "7313 Beverly Blvd. Los Angeles, CA 90036",
    phoneNumber: "(323) 297-0070",
    deliveryPartners: ["Caviar", "UberEats"],
  },
  {
    id: "m1",
    type: "movie",
    name: "Braveheart",
    genre: "War/Drama",
    releaseDate: 1995,
    duration: "3h 2m",
    rating: [8.3, 78, 68],
    watchOn: "Youtube",
    director: "Mel Gibson",
    cast: ["Mel Gibson", "Sophie Marceau", "Patrick McGoohan"],
    synopsis: `William Wallace is the medieval Scottish patriot who is spurred into revolt against the English when the love of his life is slaughtered. Leading his army into battles that become a war, his advance into England threatens King Edward I's throne before he is captured and executed, but not before becoming a symbol for a free Scotland.`,
  },
  {
    id: "m2",
    type: "movie",
    name: "Vanilla Sky",
    genre: "Thriller/Sci-fi",
    releaseDate: 2001,
    duration: "2h 17m",
    rating: [6.9, 42, 45],
    watchOn: "Tubi",
    director: "Cameron Crowe",
    cast: ["Tom Cruise", "Penélope Cruz", "Cameron Diaz"],
    synopsis: `Tom Cruise and Cameron Crowe reunite after "Jerry Maguire" for "Vanilla Sky," the story of a young New York City publishing magnate who finds himself on an unexpected roller-coaster ride of romance, comedy, suspicion, love, sex and dreams in a mind-bending search for his soul.`,
  },
  {
    id: "m3",
    type: "movie",
    name: "The Empire Strikes Back",
    genre: "Sci-fi/Action",
    releaseDate: 1980,
    duration: "2h 7m",
    rating: [8.7, 94, 82],
    watchOn: "DisneyPlus",
    director: "Irvin Kershner",
    cast: ["Mark Hamill", "Carrie Fisher", "Harrison Ford"],
    synopsis: `The adventure continues in this "Star Wars" sequel. Luke Skywalker (Mark Hamill), Han Solo (Harrison Ford), Princess Leia (Carrie Fisher) and Chewbacca (Peter Mayhew) face attack by the Imperial forces and its AT-AT walkers on the ice planet Hoth. While Han and Leia escape in the Millennium Falcon, Luke travels to Dagobah in search of Yoda. Only with the Jedi master's help will Luke survive when the dark side of the Force beckons him into the ultimate duel with Darth Vader (David Prowse).`,
  },
  {
    id: "m4",
    type: "movie",
    name: "Spider-Man: Into the Spider-Verse",
    genre: "Animation/Action",
    releaseDate: 2018,
    duration: "1h 56m",
    rating: [8.4, 97, 89],
    watchOn: "Netflix",
    director: "Peter Ramsey",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Jake Johnson"],
    synopsis: `Bitten by a radioactive spider in the subway, Brooklyn teenager Miles Morales suddenly develops mysterious powers that transform him into the one and only Spider-Man. When he meets Peter Parker, he soon realizes that there are many others who share his special, high-flying talents. Miles must now use his newfound skills to battle the evil Kingpin, a hulking madman who can open portals to other universes and pull different versions of Spider-Man into our world.`,
  },
  {
    id: "x1",
    type: "misc",
    name: "What Is This Card 1?",
  },
  {
    id: "x2",
    type: "misc",
    name: "What Is This Card 2?",
  },
];
